# Generated by Django 3.2.4 on 2024-07-30 12:56

from django.db import migrations, models
import django.db.models.deletion
import visitors.models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_camera_gate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='stream_url',
        ),
        migrations.RemoveField(
            model_name='event',
            name='camera_id',
        ),
        migrations.AddField(
            model_name='camera',
            name='mjpeg_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='camera',
            name='stream_ip',
            field=visitors.models.IPAddressField(default='127.0.0.1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camera',
            name='stream_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='camera',
            name='stream_port',
            field=models.PositiveIntegerField(default=554),
        ),
        migrations.AddField(
            model_name='event',
            name='camera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='visitors.camera'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gate',
            name='ip',
            field=visitors.models.IPAddressField(),
        ),
    ]
