# Generated by Django 4.2.3 on 2024-07-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_auto_20240730_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='camera',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
