# Generated by Django 4.2.3 on 2024-08-04 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0004_camera_password_camera_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='access_end',
            field=models.DateField(verbose_name='end of access'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='access_start',
            field=models.DateField(verbose_name='beginning of access'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='blacklisted',
            field=models.BooleanField(default=False, verbose_name='blacklisted'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='comment',
            field=models.TextField(blank=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='license_plate',
            field=models.CharField(max_length=20, unique=True, verbose_name='license plate'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='middle name'),
        ),
    ]
