# Generated by Django 4.2.3 on 2024-08-04 03:30

from django.db import migrations, models
import django.db.models.deletion
import visitors.models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0006_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.AlterModelOptions(
            name='camera',
            options={'verbose_name': 'camera', 'verbose_name_plural': 'cameras'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-timestamp'], 'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
        migrations.AlterModelOptions(
            name='gate',
            options={'verbose_name': 'gate', 'verbose_name_plural': 'gates'},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'visitor', 'verbose_name_plural': 'visitors'},
        ),
        migrations.AlterField(
            model_name='camera',
            name='gate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='visitors.gate', verbose_name='gate'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='mjpeg_path',
            field=models.CharField(blank=True, max_length=255, verbose_name='MJPEG path'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='password',
            field=models.CharField(blank=True, max_length=100, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='stream_ip',
            field=visitors.models.IPAddressField(verbose_name='stream IP'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='stream_path',
            field=models.CharField(blank=True, max_length=255, verbose_name='stream path'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='stream_port',
            field=models.PositiveIntegerField(default=554, verbose_name='stream port'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='username',
            field=models.CharField(blank=True, max_length=100, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='event',
            name='access_granted',
            field=models.BooleanField(verbose_name='access granted'),
        ),
        migrations.AlterField(
            model_name='event',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.camera', verbose_name='camera'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='license_plate',
            field=models.CharField(max_length=20, verbose_name='license plate'),
        ),
        migrations.AlterField(
            model_name='event',
            name='reason_for_refuse',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='reason for refuse'),
        ),
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='gate',
            name='ip',
            field=visitors.models.IPAddressField(verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='gate',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='gate',
            name='password',
            field=models.CharField(max_length=100, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='gate',
            name='port',
            field=models.PositiveIntegerField(verbose_name='port'),
        ),
        migrations.AlterField(
            model_name='gate',
            name='username',
            field=models.CharField(max_length=100, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='visitors.company', verbose_name='company'),
        ),
    ]
