# Generated by Django 4.2.3 on 2024-08-09 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0009_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='is_entrance',
            field=models.BooleanField(default=False, verbose_name='is entrance'),
        ),
    ]
