# Generated by Django 4.2.3 on 2024-08-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0010_camera_is_entrance'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='opened_manually',
            field=models.BooleanField(default=False, verbose_name='opened manually'),
        ),
    ]
